Algoritmo "pares_consecutivos"

Var

   x,soma: inteiro

Inicio


   escreva("Digite um numero inteiro: ")
   leia(x)

   enquanto x <> 0 faca
   
   se x % 2 <> 0 entao // para testar se ele é par ou impar
      x <- x + 1  // caso não seja, recebe mais um para ficar par
   fimse

      soma <- 5 * x + 20 //formula
      escreval("SOMA = ",soma)

      escreva("Digite um numero inteiro: ")
      leia(x)

   fimenquanto









Fimalgoritmo