Algoritmo "media_ponderada_corrigido"

Var

  a, b, c, media: real
    i, n : inteiro

Inicio


        escreva ("Quantos casos voce vai digitar? ")
        leia(n)

        para i de 1 ate n faca

        escreval ("Digite três numeros:")
        leia(a)
        leia(b)
        leia(c)
        media <- (a * 2 + b * 3 + c * 5) / 10

        escreval ("MEDIA =", media:3:1)

        fimpara




     

Fimalgoritmo
