Algoritmo "Exercicio nota"


Var

    nota1,nota2,notaFinal : real


Inicio

     escreva ( "Digite a primeira nota:")
     leia (nota1)
     escreva ( "Digite a segunda nota:")
     leia (nota2)
     
     notaFinal<- nota1 + nota2
     
     escreval ("Nota Final: ")
     
     se notaFinal >= 60 entao
     escreval ("APROVADO") // foi acrescentado aprovado e mudado >=
     senao
     escreval ("REPROVADO")
     
     fimse
       



    
    
  

  


Fimalgoritmo