Algoritmo "Teste condicional com 3 se"


Var

    hora: inteiro


Inicio

    escreva ("Digite a hora do dia:")
    leia(hora)
    
    se hora < 12 entao
       escreval ("Good Morning!")
    fimse
    
    se (hora >=12) e (hora < 18) entao
       escreval ("Good Afternoon!")
    fimse
       
       
    se hora > 18 entao
       escreval ("Good Evining!")
       
    fimse
    
    
  

  


Fimalgoritmo