Algoritmo "Teste condicional com se e senão"


Var

    hora: inteiro


Inicio

    escreva ("Digite a hora do dia:")
    leia(hora)
    
    se hora < 12 entao
       escreval ("Good Morning!")


    senao
       se (hora >= 12 ) e (hora < 18) entao
           escreval ("Good Afternoon!")
       senao
           escreval("Good Evening")
       fimse
       


    fimse
    
    
  

  


Fimalgoritmo